// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// GraphQL Schema for Member API.
// This SDL mirrors the implemented queries in the Go resolvers.
type Member struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type Query struct {
}
