package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"member_API/graphql/model"
	"member_API/models"
	"member_API/services"

	"github.com/google/uuid"
)

// CreateMember is the resolver for the createMember field.
func (r *mutationResolver) CreateMember(ctx context.Context, input model.CreateMemberInput) (*model.Member, error) {
	svc := services.NewMemberService(r.DB)

	// 從 context 取得使用者 ID（如果沒有則使用 0 表示系統建立）
	creatorId := getUserIDFromContext(ctx)

	member, err := svc.CreateMember(input.Name, input.Email, input.Password, creatorId)
	if err != nil {
		return nil, err
	}

	return dbToModel(*member), nil
}

// UpdateMember is the resolver for the updateMember field.
func (r *mutationResolver) UpdateMember(ctx context.Context, id string, input model.UpdateMemberInput) (*model.Member, error) {
	svc := services.NewMemberService(r.DB)

	memberID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("無效的會員 ID")
	}

	// 從 context 取得使用者 ID
	modifierId := getUserIDFromContext(ctx)

	member, err := svc.UpdateMember(memberID, input.Name, input.Email, modifierId)
	if err != nil {
		return nil, err
	}

	return dbToModel(*member), nil
}

// DeleteMember is the resolver for the deleteMember field.
func (r *mutationResolver) DeleteMember(ctx context.Context, id string) (bool, error) {
	svc := services.NewMemberService(r.DB)

	memberID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("無效的會員 ID")
	}

	// 從 context 取得使用者 ID
	deleterId := getUserIDFromContext(ctx)

	if err := svc.DeleteMember(memberID, deleterId); err != nil {
		return false, err
	}

	return true, nil
}

// Member is the resolver for the member field.
func (r *queryResolver) Member(ctx context.Context, id string) (*model.Member, error) {
	if r.DB == nil {
		return nil, nil
	}
	var m models.Member
	if err := r.DB.First(&m, id).Error; err != nil {
		return nil, nil
	}
	return dbToModel(m), nil
}

// Members is the resolver for the members field.
func (r *queryResolver) Members(ctx context.Context, limit *int) ([]*model.Member, error) {
	if r.DB == nil {
		return []*model.Member{}, nil
	}
	lim := 50
	if limit != nil && *limit > 0 {
		lim = *limit
	}
	var rows []models.Member
	if err := r.DB.Select("id", "name", "email", "created_at", "updated_at").Limit(lim).Find(&rows).Error; err != nil {
		return nil, err
	}
	out := make([]*model.Member, len(rows))
	for i, m := range rows {
		out[i] = dbToModel(m)
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
